CREATE TABLE `user` (
    `id` SERIAL,
	`NO` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
	`NAME` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
	`ENT_YEAR` INT(10),
	`CLASS_NUM` CHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
	`IS_ATTEND` BOOLEAN,
	`SCHOOL_CD` CHAR(3),
	PRIMARY KEY (`NO`)
) ENGINE=InnoDB;